### ISSUE TITLE
Non-tracked requirement

### ISSUE THREAD

**Issue by victorarthur** [darrynten/pslayers#24]
<img width="850" alt="screenshot 2018-02-10 12 31 22" src="https://user-images.githubusercontent.com/3355074/36061706-6d5a30f2-0e5e-11e8-89ec-d876966f3415.png">

**Comment by darrynten** [comment]
Thanks for the report.

I've opened a PR https://github.com/darrynten/pslayers/pull/25

**Comment by darrynten** [comment]
This should be resolved with PR #25
